import React from "react";
import PageHeader from "../components/PageHeader.jsx";

const SECTIONS = [
  {
    title: "1. Acceptance of terms",
    body: "By using the AI Career & Skill Recommendation System, you agree to use it for personal, educational, and evaluative purposes. This is a demonstration project built as part of an academic/internship exercise, not a commercial product.",
  },
  {
    title: "2. Nature of the recommendations",
    body: "Career recommendations are generated by a machine-learning model trained on a documented, synthetic dataset. They are suggestions based on learned patterns and the information you provide - not a guarantee of career success, employability, or fit, and not professional career counseling.",
  },
  {
    title: "3. No warranty",
    body: "The system is provided \"as is\" without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of any recommendation, skill-gap analysis, or learning roadmap produced by the system.",
  },
  {
    title: "4. Acceptable use",
    body: "You agree not to misuse the assessment form or API - for example, by submitting automated bulk requests intended to disrupt the service, or attempting to reverse-engineer the underlying model beyond what is already documented in the project's README.",
  },
  {
    title: "5. Changes to these terms",
    body: "These terms may be updated as the project evolves. Continued use of the system after changes are posted constitutes acceptance of the revised terms.",
  },
];

export default function TermsPage() {
  return (
    <div>
      <PageHeader eyebrow="Legal" title="Terms & Conditions" />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 pb-20 flex flex-col gap-8">
        {SECTIONS.map((section) => (
          <div key={section.title}>
            <h2 className="font-display font-semibold text-white">
              {section.title}
            </h2>
            <p className="mt-2 text-sm text-navy-300 leading-relaxed">
              {section.body}
            </p>
          </div>
        ))}
        <p className="text-xs text-navy-400">Last updated: 2026</p>
      </div>
    </div>
  );
}
